var data = {
  0: 'marriage_registration_office',
  1: 'neighborhood_committee',
  2: 'finance',
  3: 'social_security',
  4: 'subdistrict_office',
  5: 'local_police_station',
  6: 'management_committee',
  7: 'human_resources_and_social_security_bureau',
  8: 'civil_affairs',
  9: 'accumulation_fund',
  10: 'national_tax_bureau',
  11: 'local_tax_bureau',
  12: 'administration',
  13: 'quarantine_bureau',
  14: 'customs',
  15: 'consulate',
  16: 'party_and_government_offices',
  17: 'government',
  18: 'party_committee',
  19: 'procuratorate',
  20: 'court',
  21: 'CPPCC',
  22: 'public_security_bureau',
  23: 'standing_committee',
  24: 'office_hall',
  25: 'industrial_and_commercial_bureau',
  26: 'water_payment',
  27: 'electric_payment',
  28: '无',
  29: 'heating_payment',
  30: 'communication',
  31: 'housekeeping',
  32: 'lottery',
  33: 'law_firm',
  34: 'logistics_express',
  35: 'postal_service',
  36: 'hospital',
  37: 'maternal_children_health_care',
  38: 'emergency_center',
  39: 'family_planning',
  40: 'health_services',
  41: 'clinic',
  42: 'drugstore',
  43: 'epidemic_station',
  44: 'railway_station',
  45: 'airport',
  46: 'wharf',
  47: 'subway',
  48: 'bus_station',
  49: 'service_zone',
  50: 'highway_intersection',
  51: 'enterprise',
  52: 'institution',
  53: 'social_organization',
  54: 'research_institutes',
  55: 'tourist_attractions',
  56: 'religious_site',
  57: 'travel_agency',
  58: 'emergency_shelter',
  59: 'gerocomium',
  60: 'rescue_station',
  61: 'funeral_and_interment',
};

export default {
  data,
};
